### ISSUE TITLE
difficulty installing ThetaMater

### ISSUE THREAD

**Issue by svedwards** [radamsRHA/ThetaMater#1]
Hi Richard -

Your package looks interesting but I am having trouble installing it. Working on Mac 11.2.3 and R version 4.1.1. I installed boost, MCMCpack and Rcpp as directed but when I tried to install ThetaMater got the following. Doesn't seem to connect with boost for some reason:

> install_github("radamsRHA/ThetaMater")
Downloading GitHub repo radamsRHA/ThetaMater@HEAD
✓  checking for file ‘/private/var/folders/11/r1rvfmjd4v96b4zj0_zx2lhh0000gn/T/RtmpgAUDVp/remotes11868e7f13b6/radamsRHA-ThetaMater-02f8729/DESCRIPTION’ ...
─  preparing ‘ThetaMater’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ThetaMater_0.0.0.9000.tar.gz’
   
* installing *source* package ‘ThetaMater’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c ThetaDataLike.cpp -o ThetaDataLike.o
ThetaDataLike.cpp:3:10: fatal error: 'boost/math/special_functions/binomial.hpp' file not found
#include <boost/math/special_functions/binomial.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [ThetaDataLike.o] Error 1
ERROR: compilation failed for package ‘ThetaMater’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/ThetaMater’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/11/r1rvfmjd4v96b4zj0_zx2lhh0000gn/T//RtmpgAUDVp/file1186838e71929/ThetaMater_0.0.0.9000.tar.gz’ had non-zero exit sta
